class Solution:
    def sequentialDigits(self, low: int, high: int) -> list[int]:
        """Find all integers with sequential digits within [low, high].

        Intuition:
            Sequential digit numbers can be generated by starting from each digit 1-9
            and appending consecutive digits.

        Approach:
            For each starting digit, build numbers by appending the next consecutive
            digit. Collect those within the range [low, high] and return sorted.

        Complexity:
            Time: O(1) — at most 36 sequential digit numbers exist
            Space: O(1)
        """
        result: list[int] = []
        for start in range(1, 9):
            number = start
            for next_digit in range(start + 1, 10):
                number = number * 10 + next_digit
                if low <= number <= high:
                    result.append(number)
        return sorted(result)
